### ISSUE TITLE
queue error

### ISSUE THREAD

**Issue by neon5d** [joergfranke/ADNC#1]
Hello, I tried to run scripts/start_training.py, but I encountered the following error:
My python version is 3.5.2.
DNC-master\adnc\data\loader.py", line 124, in producer
    for item in batch_gen:
TypeError: iter() returned non-iterator of type 'dict'

**Comment by JoergFranke** [comment]
Thanks for the bug report. I fixed the BatchGenerator, it should now work.

**Comment by neon5d** [comment]
Thank you for fixing.
It works now.

**Comment by JoergFranke** [comment]
#390fb1f
